# Generated by Django 6.0 on 2025-12-03 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Fecha y hora de ejecución",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=False, help_text="Indica si el scraping fue exitoso"
                    ),
                ),
                (
                    "num_becas",
                    models.IntegerField(
                        default=0, help_text="Número de becas extraídas"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Mensaje de error si falló", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Scraping",
                "verbose_name_plural": "Logs de Scraping",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador de sesión del usuario",
                        max_length=255,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("human", "Usuario"), ("ai", "BecaBot")],
                        help_text="Rol del mensaje (humano o IA)",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(help_text="Contenido del mensaje")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Fecha y hora del mensaje",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Chat",
                "verbose_name_plural": "Mensajes de Chat",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_key", "created_at"],
                        name="myapp_chatm_session_df7228_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UploadedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador de sesión del usuario",
                        max_length=255,
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="Nombre del archivo", max_length=255),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Ruta del archivo en el sistema", max_length=500
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Fecha y hora de subida",
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el documento fue procesado en la base vectorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Subido",
                "verbose_name_plural": "Documentos Subidos",
                "ordering": ["-uploaded_at"],
                "unique_together": {("session_key", "filename")},
            },
        ),
    ]
