# Generated by Django 6.0 on 2025-12-03 19:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadeddocument",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Documento Subido (Legacy)",
                "verbose_name_plural": "Documentos Subidos (Legacy)",
            },
        ),
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("json_corpus", "Corpus JSON"),
                            ("pdf_document", "Documento PDF"),
                        ],
                        help_text="Tipo de contenido versionado",
                        max_length=20,
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(help_text="ID del objeto versionado"),
                ),
                (
                    "version_number",
                    models.CharField(help_text="Número de versión", max_length=50),
                ),
                (
                    "file_backup",
                    models.FileField(
                        help_text="Copia de respaldo del archivo",
                        upload_to="versions/%Y/%m/",
                    ),
                ),
                (
                    "change_description",
                    models.TextField(
                        blank=True, help_text="Descripción de los cambios"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Fecha de creación de la versión",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Usuario que creó la versión",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Versión de Archivo",
                "verbose_name_plural": "Versiones de Archivos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="myapp_filev_content_c2f71e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JSONCorpus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre identificador del corpus (ej: 'becas_utpl_2024')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "corpus_type",
                    models.CharField(
                        choices=[
                            ("becas", "Corpus de Becas"),
                            ("faqs", "Preguntas Frecuentes"),
                            ("general", "Datos Generales"),
                            ("custom", "Personalizado"),
                        ],
                        default="general",
                        help_text="Tipo de corpus de datos",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descripción del contenido del corpus"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Archivo JSON con el corpus de datos",
                        upload_to="corpus_json/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["json"]
                            )
                        ],
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Versión del corpus (ej: 1.0, 2024-Q1)",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si este corpus está activo para uso",
                    ),
                ),
                (
                    "records_count",
                    models.IntegerField(
                        default=0, help_text="Número de registros en el corpus"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0, help_text="Tamaño del archivo en bytes"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Usuario que creó el corpus",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Corpus JSON",
                "verbose_name_plural": "Corpus JSON",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["corpus_type", "is_active"],
                        name="myapp_jsonc_corpus__5b8e51_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="myapp_jsonc_created_1be8a5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PDFDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Título del documento", max_length=250),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("report", "Reporte"),
                            ("guide", "Guía"),
                            ("manual", "Manual"),
                            ("regulations", "Reglamento"),
                            ("form", "Formulario"),
                            ("other", "Otro"),
                        ],
                        default="report",
                        help_text="Tipo de documento",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descripción del contenido"),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Archivo PDF",
                        upload_to="documents_pdf/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, help_text="Versión del documento", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicado"),
                            ("archived", "Archivado"),
                        ],
                        default="draft",
                        help_text="Estado del documento",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Etiquetas separadas por comas (ej: becas,postgrado,2024)",
                        max_length=500,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="¿Documento público para descarga?"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0, help_text="Tamaño del archivo en bytes"
                    ),
                ),
                (
                    "page_count",
                    models.IntegerField(
                        blank=True, default=0, help_text="Número de páginas del PDF"
                    ),
                ),
                (
                    "processed_for_vectordb",
                    models.BooleanField(
                        default=False,
                        help_text="¿Procesado en la base de datos vectorial?",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Usuario que subió el documento",
                        max_length=100,
                    ),
                ),
                (
                    "related_corpus",
                    models.ForeignKey(
                        blank=True,
                        help_text="Corpus JSON relacionado (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_pdfs",
                        to="myapp.jsoncorpus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento PDF",
                "verbose_name_plural": "Documentos PDF",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document_type", "status"],
                        name="myapp_pdfdo_documen_c004ea_idx",
                    ),
                    models.Index(
                        fields=["is_public"], name="myapp_pdfdo_is_publ_754a1a_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="myapp_pdfdo_created_5a8dec_idx"
                    ),
                ],
            },
        ),
    ]
